#Consul UI available at:   http://localhost:8500/ui
#Kafka UI available at:    http://localhost
#Using this docker-compose file, it's possible to scale kafka, just verify in Consul that zookeeper is ready before scaling Kafka.
zookeeper:
    image: vescel/zookeeper
    env_file: _env
    ports:
       - 2181
       - 2888
       - 3888